name: Greetings

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build the project
        working-directory: java-app
        run: mvn clean install
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: 'java-app/target/demo-0.0.1-SNAPSHOT.jar'
