name: Greetings

on:
  issues:
  pull_request:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: ashwin-ant/action-test-publish@newtag
        with:
          message: Hello my friend !
      - uses: kyoncy/issue-comment-actions@v1
        with:
          message: This is a comment on the issue
