name: Greetings

on:
  issues:
  pull_request:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: ashwin-ant/action-test-publish@newtag
        with:
          message: Hello my friend !
      - uses: actions/first-interaction@v1.3.0
        with:
          issue-message: This is a comment on the issue
