name: Greetings

on:
  issues:
  pull_request:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: ashwin-ant/action-test-publish@newtag
        with:
          message: Hello my old friend !
      - uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "This is a comment on the issue"
